examples/leaderboard/leaderboard.html
examples/leaderboard/leaderboard.jsx
examples/leaderboard/player.jsx

Hello,
I noticed that some of the examples were not following common React patterns. I refactored the Leaderboard app a bit to conform more closely to React idioms. This changed the structure a little more that I anticipated so I hope it's not going too far. I can also split `PlayerItem` out into another file too.
Would you be open to converting the increment button section to a react template too? This would leave Blaze to handle just the HTML static shell.
Ideally from a React perspective there would be a topmost `LeaderBoardContainer` React component wrapping both the increment component and `PlayerList` component and that would get inserted into the body but I wasn't sure how much of the Blaze logic you wanted to leave.
Cheers!
Adam

Refactor Leaderboard App

---

packages/react-meteor-data/meteor-data-mixin.jsx

When using the mixin `ReactMeteorData`, it is not taking into account that it might be executed on the server. Because it uses the Tracker (and it doesn't work on the server), it throws this error:
```
I20150730-19:37:02.216(-4)? Exception in callback of async function: Error: Can't call yield in a noYieldsAllowed block!
I20150730-19:37:02.217(-4)?     at Function.Fiber.yield (packages/meteor/fiber_helpers.js:8:1)
I20150730-19:37:02.218(-4)?     at Function.wait (/home/benoit/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:183:14)
I20150730-19:37:02.218(-4)?     at Object.Future.wait (/home/benoit/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-o …
```

Fix react-meteor-data for server rendering

---

packages/jsx/jsx-plugin.js
packages/jsx/package.js

Only merge this when the following commit is published as a 1.2 RC: https://github.com/meteor/meteor/commit/291c8fe344de78ce98ce16af9a993e348bff000b
Don't forget to update the `babel-compiler` reference in `packages/jsx/package.js` to the new version.

Use the BabelCompiler exported by babel-compiler

---

packages/react-runtime/react-runtime.js

ReactDOMServer is undefined because it was missing the Dev/Prod suffix.

Fix ReactDOMServer undefined

---

packages/react-runtime-dev/package.js
packages/react-runtime-prod/package.js

When browserifying a file in both the client and server scope with different exports the `getCacheKey()` of cosmos:browserify doesn't work right because it considers the `file.getDeclaredExports()`. Version 0.8.3 avoids the problem by not including the exports in the cache key.
See [this issue](https://github.com/elidoran/cosmos-browserify/issues/29) for babble about it.

update cosmos:browserify to 0.8.3 to fix cache use

---

packages/react-runtime/react-runtime.js

Right now, React DOM Server is not exposing properly. This will fix it.

Fix the typo error which does not expose ReactDOMServer

---

packages/react-runtime-dev/react.browserify.options.json
packages/react-runtime-prod/react.browserify.options.json

This file (from Polymer) includes some ES5 getters which are incompatible with IE8. We include it incase people want to `require('react/lib/webcomponents)`, however I don't think this file is truly a part of react (I think it ends up in the npm module by accident perhaps? not sure).
See https://github.com/meteor/meteor/issues/5791

Remove webcomponents.js from includes list.

---

packages/react-template-helper/react-template-helper.js

I ran into a case where the ```onRendered``` callback hadn't been called yet, but the ```onDestroyed``` was called first. Currently my workaround is to create a div ```onCreated``` and set ```this.container``` equal to it, but it would be nice if this was fixed in the package by ensuring that ```this.container``` is set before trying to utilize it.

ensure this.container is set in the onDestroyed callback before passing to ReactDOM to unmount it

---

packages/react-meteor-data/README.md

React article] -> [React article]

Fix markdown typo in 'React article' link

---

packages/react-meteor-data/README.md
packages/react-meteor-data/createContainer.jsx
packages/react-meteor-data/package.js
packages/react-meteor-data/react-meteor-data.jsx

React 15.5 has deprecated React.createClass. This fixes that. Prompted by [this issue](https://github.com/meteor/meteor/issues/8625)

Switch to create-react-class

---

packages/react-meteor-data/README.md
packages/react-meteor-data/ReactMeteorData.jsx
packages/react-meteor-data/createContainer.jsx
packages/react-meteor-data/package.js
packages/react-meteor-data/react-meteor-data.jsx

Converts the ReactMeteorData mixin to a [Higher-Order Component](https://facebook.github.io/react/docs/higher-order-components.html)
This PR fixes warnings with latest React like:
* React.createClass is deprecated and will be removed in version 16.
Fixes #216
Closes #200 
(maybe more)

Convert ReactMeteorData to a Higher-Order Component

---

packages/react-meteor-data/ReactMeteorData.jsx
packages/react-meteor-data/react-meteor-data.jsx

This PR is intended to help resolve backwards compatibility issues that were introduced in PR #217, and will fix #223. The newer HOC approach is maintained with these changes, but the pre-existing `ReactMeteorData` object is preserved and exported, which allows people using mixin approaches to continue using the latest version of this package. 
We should probably consider releasing a beta version with these changes.

Restored the ReactMeteorData object so it can still be used with mixins.

---

packages/react-meteor-data/package.js
packages/react-meteor-data/react-meteor-data.jsx

This PR updates the `checkNpmVersions` range for React to fix the
```
WARNING: npm peer requirements (for react-meteor-data) not installed:
- react@16.0.0 installed, react@15.x needed
```
warning if React 16 is installed. I also updated the version range for React 15 (from 15.x to ^15.3) because 15.3.0 is the oldest version that works with `react-meteor-data`.
Fixes #214

Update version range for React 15 & 16

---

packages/react-meteor-data/ReactMeteorData.jsx
packages/react-meteor-data/createContainer.jsx
packages/react-meteor-data/react-meteor-data.jsx
packages/react-meteor-data/withTracker.jsx

Required a bit of refactoring. It makes much more sense to directly export the `connect` function as `withTracker`.

add deprecation warning to createContainer

---

packages/react-template-helper/react-template-helper.js

The check has been obsolete since Meteor 1.2; I confirmed that the
existing dependencies of this react-template-helper version prevent
installing it on Meteor versions older than 1.2.  The check is giving me
false failures when the React component itself renders multiple nodes.

react-template-helper: Remove the check that the component is the only child of its parent element.

---

packages/react-meteor-data/package.js

Simply makes the main module [lazy](https://docs.meteor.com/packages/modules.html#Lazy-loading-modules-from-a-package).
Also closes #265

Make module lazy

---

packages/react-meteor-data/withTracker.tsx

With the conversion TypeScript, I missed setting the default of pure to true in `withTracker`. This PR fixes it. Fixes issue #287.

Make pure default to true like it used to - fix #287

---

packages/react-mongo/react-mongo.ts

The subscription needs to be started within the `Tracker.autorun` context, otherwise it's not stopped when hook is cleaned up.

Fix subscriptions not closed when stopping computation

---

packages/react-template-helper/README.md

Markdown typo prevented link from formatting

Fix typo in README

---

packages/react-meteor-data/package.js

We don't need to specify version constrains on core packages [when using `versionsFrom`.](https://docs.meteor.com/api/packagejs.html#PackageAPI-versionsFrom)
There is also nothing in this implementation that specifically requires the latest version of Meteor or the typescript package, so we should probably specify a range.

Remove version  constraint on core typescirpt package

---

packages/react-meteor-data/useTracker.tests.js
packages/react-meteor-data/useTracker.ts

- Fixes an edge case bug where Subscriptions could get lost or thrash, when using deps, and if the render is not mounted quickly enough. All of that timeout workaround stuff has been removed and replaced with a much more clean "react" implementation.
- Cleans up typescript defs
- Add resubscribe tests for with deps variant, and reorg test groupings
- Simplifies implementation
- Removes undocumented computation handler
The runtime performance characteristics of the hook changed enough to warrant a minor version bump.

Fix issue with useTracker and Subscriptions when using deps

---

packages/react-meteor-data/useTracker.ts

Fixes a regression in the dev mode input checks. `deps` should only be validated as an `Array` when they are provided. The hook allows for `deps` to be undefined.

Only validate deps are an Array when provided

---

packages/react-meteor-data/useTracker.tests.js
packages/react-meteor-data/useTracker.ts

This attempts to fix various lost reactivity reports, as well as some trouble with a particular "Maximum update depth exceeded" error, coming from (possibly) constantly updating `deps` interaction with `useEffect`, in two ways:
- Adds guards against containing computations effecting the enclosed computation in `useEffect`.
- Adds a system to keep the reference to `reactiveFn` always up to date with the latest render.
All tests are passing, but I'd like to see if we can work out a test to confirm the reported error.
#313

Fix lost reactivity when using deps

---

packages/react-meteor-data/README.md
packages/react-meteor-data/package-lock.json
packages/react-meteor-data/package.json
packages/react-meteor-data/useTracker.tests.js
packages/react-meteor-data/useTracker.ts
packages/react-meteor-data/withTracker.tests.js
packages/react-meteor-data/withTracker.tsx

This adds a comparator argument as the 2nd or third argument.
It also fixes an issue that can occur when an immediate rerender occurs. This can happen when a state setter is called during render. In such cases, React immediately runs the rerender without additional lifecycle stages.
This PR contains tests and readme edits for everything.

Fix data loss with immediate rerender, and add comparator argument

---

packages/react-meteor-accounts/CHANGELOG.md
packages/react-meteor-accounts/README.md

Adds a changelog file, general information to the readme like table of contents, installation info, and api documentation for the exported functions.

chore(react-meteor-accounts): add changelog; readme info and api docs

---

packages/react-meteor-data/README.md

Improves react-meteor-data's README by adding a table of contents, rearranging heading orders, fixing typos, and fixing markdown lint warnings.
Reasoning for a TOC: Since this README serves as the package's documentation, it should be more easily navigable. A user shouldn't have to guess or scroll through other long sections to see what else the docs contain.
_p.s._ a better name for this package might have been "react-tracker" but 🤷🏻.

chore(react-meteor-data): add readme toc; fix typos, md lint

---

packages/react-meteor-accounts/README.md
packages/react-meteor-accounts/index.tests.ts
packages/react-meteor-accounts/index.ts
packages/react-meteor-accounts/package-lock.json
packages/react-meteor-accounts/package.js
packages/react-meteor-accounts/package.json
packages/react-meteor-accounts/react-accounts.tests.tsx
packages/react-meteor-accounts/react-accounts.tsx
packages/react-meteor-accounts/tsconfig.json
packages/react-meteor-accounts/types/react-accounts.d.ts

Apologies for a large PR. I can split it up if needed.
Accomplished tasks:
- Added dependency on `"accounts-base"`.
- Otherwise, the properties used would not exist on `Meteor.*`.
- **Edit: I believe this is good reason to switch to using `Accounts.*` instead, but that's also trivial.**
- Corrected TS function signatures.
- HOCs are apparently hard to type! but I looked around at some other major react packages and did what I thought was reasonable and works as demonstrated in the tests.
- ~_side note:_ TS wrongly excludes `null` from the returns types of `Meteor.userId` / `Meteor.user`, not sure why... but that's why the corresponding hooks have explicit signatures~ **Edit: Solved**
- Ran the types script again; updated the README
- Added check for at least React v16.8
- Added JSDoc …

feat(react-meteor-accounts): fixes types, deps; adds React check, loggingIn/Out sources, tests

---

packages/react-meteor-data/CHANGELOG.md
packages/react-meteor-data/package-lock.json
packages/react-meteor-data/package.js
packages/react-meteor-data/package.json
packages/react-meteor-data/useTracker.tests.js
packages/react-meteor-data/useTracker.ts

Fixes useTrackerNoDeps for React 18
Also re-adds an attempt to retain the "side-effect"
we are creating during first render, when we can,
to both versions of the hook
The tests don't work with react 18 because the testing framework requires updating, and that breaks things. It's important to get those tests working again before we ship this, because they test important edge cases.

Fix useTrackerNoDeps for React 18

---

packages/react-meteor-data/useFind.ts

Modification implemented as suggested in section 4.2. https://github.com/meteor/react-packages/pull/360#issuecomment-1290668953.
It removes the `fetch` function call and adds a data initializer made with cursor observing.

Modified useFindClient hook

---

packages/react-meteor-data/useFind.ts

Fix https://github.com/meteor/react-packages/issues/369
Data returned by `useFind` wasn't updated if the cursor was changed. It happened because the initial fetch was called only once.
I added the initial fetch also to the `useEffect` hook. It will be called only if the cursor is updated.

Fix useFind

---

packages/react-template-helper/react-template-helper.js

Fixes:
```
WARNING: npm peer requirements (for react-template-helper) not installed:
- react@18.2.0 installed, react@15.3 - 17 needed
- react-dom@18.2.0 installed, react-dom@15.3 - 17 needed
Read more about installing npm peer dependencies:
http://guide.meteor.com/using-packages.html#peer-npm-dependencies
```

fix(PeerDeps): Fixes peerDependencies after upgrading to support react 18

---

packages/react-meteor-data/useFind.ts

I fixed the behavior of `useFind` to pass a test in a `useFind.tests.js`.
```js
const docs = useFind(() => returnNull ? null : TestDocs.find(), [returnNull])
```
1. `useFind` can accept `() => null` as argument. Previously it returned `null` in this scenario, so I changed the return statement because it was returning an empty array.
2. I also added setting the `didMount` flag before checking if the cursor is `null` or `undefined`. Without this, example above will return an empty array if `returnNull` will change to `false`

Fix useFind if cursor has no value

---

packages/react-meteor-data/package-types.json
packages/react-meteor-data/package.js
packages/react-meteor-data/react-meteor-data.d.ts

Types are taken from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/meteor/react-meteor-data.d.ts and updated to match the latest release.

Add types for react-meteor-data package

---

packages/react-meteor-data/package.js
packages/react-meteor-data/useTracker.ts

Video for reproducing the issue as shown in #382
https://user-images.githubusercontent.com/70247653/216427576-11237efd-bcc9-468d-812e-3aa61273ecdb.mov
closes #382
closes #381
closes #351

Solving memory leak in useTracker

---

packages/react-meteor-data/package-types.json
packages/react-meteor-data/package.js

This is a followup to #377 based on my best understanding of how `zodern:types` expects type declarations to appear.
(FYI @zodern @piotrpospiech @radekmie in case any of y'all see something I've missed)
As discussed on #377, the current configuration does not seem to allow `zodern:types` to detect the type declarations for `react-meteor-data`. As I understand it, the current configuration doesn't work is because `react-meteor-data.d.ts` is being included as both an asset and as a source file. You can see this by looking at `~/.meteor/packages/react-meteor-data/2.6.2/os.json` (and similarly the files for `web.browser.json` and `web.browser.legacy.json`). This is because, in addition to explicitly including the definition file as an asset, the `typescript` package includes any `.ts` file …

Remove duplicate copy of react-meteor-data.d.ts from isopack

---

packages/react-meteor-data/package.js
packages/react-meteor-data/suspense/useSubscribe.ts

This issue was reported in our [Discord](https://discord.com/channels/1247973371040239676/1273201326318162001/1273201326318162001).
This is a video showing the issue:
https://github.com/user-attachments/assets/7490bcb1-dc34-4c39-a2a3-f84f14338156
If you check the part of the code where [we call `useSubscribe`,](https://github.com/kolyasya/meteor-sub-issue/blob/main/imports/ui/Info.jsx#L47), the params remain the same.
However, the cleanup of the `useEffect` is still triggered because we change the object reference after unmounting the page.
To solve this, we're now stringifying the params. This could cause an issue in different scenarios if the object is too big, but in this case, we are stringifying the parameters for a subscription, so it's unlikely this object will cause any issue. …

Stringify params for useSubscribe to avoid stopping the subscription when object reference changes

---

packages/react-meteor-data/suspense/useSubscribe.ts

The useSubscribe suspense throws an error when run in the server environment, the code is similar to a normal useSubscribe and is intended to run only on the client.
```ts
const useSubscribeSuspenseServer = (name?: string, ...args: any[]) => undefined;
export const useSubscribeSuspense = Meteor.isServer
? useSubscribeSuspenseServer
: useSubscribeSuspenseClient
```

Fix useSubscribe suspense does not work at SSR

---

tests/react-meteor-accounts-harness/package-lock.json
tests/react-meteor-accounts-harness/package.json
tests/react-meteor-data-harness/package-lock.json
tests/react-meteor-data-harness/package.json

This PR updates test runner dependencies of React to latest 18.x version.
React 19.x has warning with `@testing-library/react` which requires at maximum 18.x. That is why I upgrade to 18.x.

Ensure compatibility with latest React

---

packages/react-meteor-data/useFind.tests.js
packages/react-meteor-data/useFind.ts

Add a test that catches the issue https://github.com/meteor/react-packages/issues/418
I am skipping the test because it is failing with the current code
So this is not a fix attempt anymore, but just add the test for someone who will try to fix it

Test for concurrency issue with use find client

---

packages/react-meteor-data/useFind.ts

useFind default behavior is to have a void array as deps. This is confusing and leading to bugs hard to find.
useFind should work like useMemo, useEffect and usedTracker, having an undefined deps by default

UseFind should work like other hooks

---

packages/react-meteor-data/suspense/useFind.tests.js
packages/react-meteor-data/suspense/useFind.ts

In the client-side implementation of `suspense/useFind`, useFindClient is used. PR #418 introduced `useSyncEffect`. 
Nevertheless, when used in **Strict Mode** and with **Suspense**, the `useSyncEffect` implementation results in non-trivial and hard-to-predict issues.
As a result, the Suspense-enabled `useFindSuspenseClient` will no longer reference `useFindClient` and will instead be a standalone implementation (derived from the last stable version of `useFindClient`).
Note: The #418 test case issue does not occur with React 18/19's `createRoot` when using `Suspense` (the test passes normally in this configuration).

fix: #443 useSyncEffect Breaks useFind Reactivity Under Suspense

---

packages/react-meteor-data/suspense/useFind.ts

This PR fixes typescript syntax on latest changes in order to ensure proper typescript compilation when using SWC in Meteor 3.3.
This was suddenly triggering a Babel fallback.

Fix TS syntax to favor SWC compilation

---

packages/react-meteor-data/suspense/useSubscribe.tests.js
packages/react-meteor-data/suspense/useSubscribe.ts

Strictly speaking, this is indeed a bug. While it doesn’t break the app, it can lead to a poor user experience in specific scenarios:
> When two or more identical subscriptions are active simultaneously, unmounting one of them may cause the other subscription’s nearest Suspense boundary to revert to its fallback state.
This issue typically occurs in complex applications.
---
This PR primarily introduces a reference counter.  The subscription will only be cleared when the counter reaches zero, indicating that no components are actively consuming it.

perf(suspense): optimize handling of multiple suspense/useSubscribe

---

packages/react-meteor-data/index.ts
packages/react-meteor-data/package-types.json
packages/react-meteor-data/package.js

Fixes #432 
Wasn't sure what the strategy is for this repo as there is no dev or stable branch, so I just worked off of the master branch version (Meteor Package version 3.0.5-beta.0).
According to https://packosphere.com/meteor/react-meteor-data the latest stable version of the package is 3.0.3. Would be great to get this merged into 3.0.4 stable, unless a 3.0.5 is coming out soon.

react-meteor-data: restore TS support via zodern:types
