docs/tutorial.md

React.render() gets as first parameter - component element `<App />` not component class App. 
In second case we get Error:
```
Uncaught Error: Invariant Violation: React.render(): Invalid component element. 
Instead of passing a component class, make sure to instantiate it by passing it to React.createElement.
```

fix docs to valid React.render() component element

---

docs/tutorial.md

Just fixed a couple of problems with the code

fixes for step 3 code

---

docs/tutorial.md

This commit fixes issue #23 by changing the tutorial to mount to a container div instead.
Putting the root React app into document.body can cause a lot of
unforeseen problems with browser extensions and other JS that append to
body.

Fixes Issue #23 by Mounting to Container Div

---

packages/babel-compiler/babel.js
packages/babel-compiler/package.js
packages/babel-tests/transpile-tests.jsx

Tested with
```sh
cd path/to/react-packages/packages/babel-tests
PACKAGE_DIRS=.. meteor test-packages ./
```

Use meteor-babel NPM package instead of using babel-core directly.

---

examples/leaderboard/player.jsx
examples/react-todos/client/components/AppBody.jsx
examples/react-todos/client/components/AppLoading.jsx
examples/react-todos/client/components/AppNotFound.jsx
examples/react-todos/client/components/ConnectionIssueDialog.jsx
examples/react-todos/client/components/ListShow.jsx
examples/react-todos/client/components/MenuOpenToggle.jsx
examples/react-todos/client/components/TodoItem.jsx
examples/react-todos/client/components/accounts/AuthErrors.jsx
examples/react-todos/client/components/accounts/AuthFormInput.jsx
examples/react-todos/client/components/accounts/AuthJoinPage.jsx
examples/react-todos/client/components/accounts/AuthSignInPage.jsx
examples/react-todos/client/components/accounts/UserSidebarSection.jsx

Hi there! Nice to meet you all! Here is a cleanup as proposed in issue #47 to remove the @jsx React.DOM declaration from the top of the files in the examples directory.

Examples cleanup for issue #47

---

examples/react-todos/client/components/todo-list/TodoListHeader.jsx

The input is not the target event, so new task text is not added properly. Added a ref to the input and use it to retrieve the text.

Bug adding new task in React-ToDos example

---

packages/react-meteor-data/meteor-data-mixin.jsx

Check for Mongo existence outside key checks

---

packages/react-meteor-data/.versions
packages/react-meteor-data/package.js
packages/react-runtime-dev/.npm/package/npm-shrinkwrap.json
packages/react-runtime-dev/.versions
packages/react-runtime-dev/package.js
packages/react-runtime-prod/.npm/package/npm-shrinkwrap.json
packages/react-runtime-prod/.versions
packages/react-runtime-prod/package.js
packages/react-runtime/.versions
packages/react-runtime/package.js
packages/react-template-helper/.versions
packages/react-template-helper/package.js
packages/react/.versions
packages/react/package.js

Feel free to lay the smack down on this PR if I did something wrong :)

Updated to React 0.14.3

---

docs/client-npm.md

Remove comments in json throwing a syntax error

---

packages/react-meteor-data/README.md
packages/react-meteor-data/package.js
packages/react-meteor-data/react-meteor-data.jsx
packages/react-meteor-data/withTracker.jsx

add withTracker to react-meteor-data

---

packages/react-template-helper/react-template-helper.js

Updated file similar to #232, haven't tested it.

Update version range to include React 16

---

packages/react-meteor-data/.versions
packages/react-meteor-data/package.js
packages/react-runtime/.versions
packages/react-runtime/package.js
packages/react-template-helper/.versions
packages/react-template-helper/package.js
packages/react/.versions
tests/react-meteor-data-harness/.meteor/versions
tests/react-runtime-harness/.meteor/versions
tests/react-template-helper-harness/.meteor/versions

Update check-npm-versions to 0.3.2

---

package.json

Update eslint, eslint-plugin-react, and eslint-config-airbnb. This allows the use of async/await.

Update eslint, eslint-plugin-react, and eslint-config-airbnb

---

packages/react-meteor-data/useTracker.js

When the hook is used without deps (including through `withTracker`), the component will not update correctly on the second render. This PR solves that by always forcing render after the render is committed in `withTracker`.

Fix component doesn't update without deps in StrictMode - fixes #278

---

packages/react-template-helper/package.js

Update tmeasday:check-npm-versions to v1 in react-template-helper

---

packages/react-meteor-data/README.md

Fix a tiny typo in the readme (reacitve -> reactive)

---

packages/react-meteor-data/index.js
packages/react-meteor-data/useSubscribe.ts
packages/react-meteor-data/useTracker.tests.js
packages/react-meteor-data/useTracker.ts
packages/react-meteor-data/withTracker.tests.js
packages/react-meteor-data/withTracker.tsx

Fix this one: https://github.com/Akryum/meteor-vite/pull/1#issuecomment-1328079910

fix: named exports for useTracker and withTracker

---

.eslintrc.js
packages/react-meteor-data/CHANGELOG.md
packages/react-meteor-data/README.md
packages/react-meteor-data/package.js
packages/react-meteor-data/react-meteor-data.d.ts
packages/react-meteor-data/suspense/index.js
packages/react-meteor-data/suspense/react-meteor-data.d.ts
packages/react-meteor-data/suspense/useTracker.ts

Still missing a few pieces (it works, but it has some things that need to be solved)
I will list the issue that I think needs to be solved before this goes out:
<details>
<summary>For testing this change</summary>
```ts
import { EJSON } from 'meteor/ejson';
import { Meteor } from 'meteor/meteor';
import React, { Fragment, Suspense, useCallback, useEffect, useMemo, useState } from 'react';
import { LinksCollection } from '../api/links';
import isEqual from 'lodash/isEqual';
const cachedSubscriptions: SubscriptionEntry[] = [];
type SubscriptionEntry = {
params: EJSON[];
name: string;
handle?: Meteor.SubscriptionHandle;
promise: Promise<unknown>;
result?: Meteor.SubscriptionHandle;
error?: unknown;
};
const removeFromArray =
<T>(list: T[], obj: T): void => {
if (obj) {
const index = …
```

Feat: useTracker with suspense

---

packages/react-meteor-data/CHANGELOG.md
packages/react-meteor-data/package.js
packages/react-meteor-data/suspense/react-meteor-data.d.ts
packages/react-meteor-data/suspense/useFind.ts

Relates to https://github.com/meteor/react-packages/issues/388

Updating types and isomorphism

---

.github/workflows/test-react-packages.yml
packages/react-meteor-data/package.js
packages/react-meteor-data/useFind.tests.js
tests/react-meteor-accounts-harness/package-lock.json
tests/react-meteor-accounts-harness/package.json
tests/react-meteor-data-harness/package-lock.json
tests/react-meteor-data-harness/package.json

Continues: https://github.com/meteor/react-packages/pull/422
This PR makes sure the CI runs the tests in this repository, providing quick feedback on changes before publishing new versions.

CI support (GA runner)

---

packages/react-meteor-data/useFind.ts

cherrying pick [this](https://github.com/meteor/react-packages/pull/431) PR's commit to the right branch (R4.0.0) after removing from master

UseFind should work like other hooks
